version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - frontend
    networks:
      - mern-network
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CANVAS_RSVG=0
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge