version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    networks:
      - mern-network
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CANVAS_RSVG=0
    command: npm run dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend_vite_dev
    working_dir: /app
    ports:
      # Vite dev server mặc định chạy ở cổng 5173.
      # Đảm bảo cổng này khớp với cổng mà dev server của bạn lắng nghe bên trong container.
      # Nếu bạn đã cấu hình Vite chạy ở cổng khác, hãy cập nhật ở đây.
      - "5173:5173"
    env_file:
      - ./client/.env
    networks:
      - mern-network
    volumes:
      # Mount mã nguồn của frontend từ host vào container để hot-reload
      - ./client:/app
      # Ngăn Docker ghi đè thư mục node_modules bên trong container
      - /app/node_modules


networks:
  mern-network:
    driver: bridge